
;;***************************************
;;***** USER PROGRAM INLUDE FILE*********
;;***************************************

;=-------------------------------
;=INCLUDE LIBRARY               -
;=EXTERNAL REFERENCE FILE       -
;=-------------------------------
INCLUDE "..\TKS_GLOBE_VARIES.INC"
;INCLUDE "..\BS83B04A_LIBV413\BS83B04A_LIBV413.AEX"
INCLUDE "..\BS83B12A_LIBV413\BS83B12A_LIBV413.AEX"
;INCLUDE "..\BS82C16A_LIBV413\BS82C16A_LIBV413.AEX"













